api:
  baidu_translate:
    app_id: "20220512001213099"  # 替换为实际值
    app_key: "UjMFiynp8pMsO14rbn89"
    api_url: "https://fanyi-api.baidu.com/api/trans/vip/translate"
  dictionaryapi:
    api_url: "https://api.dictionaryapi.dev/api/v2/entries/en"

  Qwen:
      api_url: "https://api.qwen.ai/v1/chat/completions"
      api_key: "your_api_key_here"  # 替换为实际值

# 调度器配置
scheduler:
  # 文章列表获取配置
  article_fetch:
    # 执行时间（凌晨2点）
    hour: 10
    minute: 0

  # 文章处理配置
  article_process:
    # 间隔时间（分钟）
    interval_minutes: 10

  # 并发处理配置
  concurrency:
    # 最大并发数
    max_concurrent: 3

# 网站配置
websites:
  # 定义通用的请求头配置
  defaults: &default_settings
    headers: &default_headers
      accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
      accept-language: "zh-CN,zh;q=0.9,en;q=0.8"
      user-agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
    cookies: {}

  # CSMonitor网站配置
  csmonitor:
    # 板块配置
    sections:
      # 单级路径
      business:
        url: "https://www.csmonitor.com/Business"
        <<: *default_settings

      # 双级路径
      arts:
        url: "https://www.csmonitor.com/The-Culture/Arts"
        <<: *default_settings

      # 单级路径
      world:
        url: "https://www.csmonitor.com/World"
        <<: *default_settings

      # 单级路径
      usa:
        url: "https://www.csmonitor.com/USA"
        <<: *default_settings