# 调度器配置
scheduler:
  # 文章列表获取配置
  article_fetch:
    # 执行时间（凌晨2点）
    hour: 10
    minute: 0

  # 文章处理配置
  article_process:
    # 间隔时间（分钟）
    interval_minutes: 10

  # 并发处理配置
  concurrency:
    # 最大并发数
    max_concurrent: 3